<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>pnkx</artifactId>
        <groupId>com.pnkx</groupId>
        <version>3.3.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>pnkx-blog</artifactId>

    <description>
        博客模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.pnkx</groupId>
            <artifactId>pnkx-common</artifactId>
        </dependency>
        <!-- 网关模块-->
        <dependency>
            <groupId>com.pnkx</groupId>
            <artifactId>pnkx-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.13.1</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
